name: Github Pages Update

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  STORYBOOKS: react

jobs:
  update-gh-pages-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish storybooks into gh-pages
        run: |
          set -x
          git config --global user.name "gh-action-run-id-${GITHUB_RUN_ID}"
          git config --global user.email 'gh-action@users.noreply.github.com'
          git pull || true
          git branch -D gh-pages || true
          git branch gh-pages
          git checkout gh-pages
          npm i
          for storybook in $STORYBOOKS
          do
            mkdir -p ${storybook}/public
          done
          npm run build:react
          for storybook in $STORYBOOKS
          do
            ln -s ${storybook}/storybook-static ${storybook}-storybook
            git add ${storybook}-storybook ${storybook}/storybook-static
            git commit -am "chore(storybook): updated ${storybook}-storybook (automatic commit done by github-action-run-id: ${GITHUB_RUN_ID})"
          done
          git push -f origin gh-pages
