name: Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🚀 release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          monorepo-tags: true
  publish-core-library:
    environment: CI
    runs-on: ubuntu-latest
    if: "endsWith(github.event.head_commit.message, 'release-please--branches--main--components--cardano-connect-with-wallet-core')"
    defaults:
      run:
        working-directory: ./core
    steps:
      - uses: actions/checkout@v3
      - name: 🫡 Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '18.12.0'
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Install dependencies
        run: npm ci
      - name: 📦 Bundle package
        run: npm run bundle
      - name: 🚀 Publish packages on npmjs
        run: npm publish
    env:
      NPM_TOKEN: ${{ secrets.NPMJS_SECRET }}
  publish-react-library:
    environment: CI
    runs-on: ubuntu-latest
    if: "endsWith(github.event.head_commit.message, 'release-please--branches--main--components--cardano-connect-with-wallet')"
    defaults:
      run:
        working-directory: ./react
    steps:
      - uses: actions/checkout@v3
      - name: 🫡 Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '18.12.0'
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Install dependencies
        run: npm ci
      - name: 🧵 Install rollup
        run: npm i -g rollup
      - name: 📦 Bundle package
        run: npm run bundle
      - name: 🚀 Publish packages on npmjs
        run: npm publish
    env:
      NPM_TOKEN: ${{ secrets.NPMJS_SECRET }}
