name: Create Release

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🚀 release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          monorepo-tags: true
