name: Run Tests
on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  test-react-libary:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/react
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🫡 Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.0

      - name: 🧘‍♀️ Download dependencies
        run: npm ci

      - name: 🎳 Run tests
        run: npm test
